<!--各controller/action刷新的内容-->
<div id="content">
	<div class="top">
		<div class="left"></div>
		<div class="right"></div>
		<div class="center">
			<h1>订单提交失败！</h1>
		</div>
	</div>
	<div class="middle">
		<div class="content">
			<p>订单提交失败！</p>
			<p>
				如有任何疑问，访问：<a href="index.php?r=information/contact">怡美店主</a>.
			</p>
			<p>感谢您光临本店</p>
		</div>
		<div class="buttons">
			<table>
				<tbody>
					<tr>
						<td align="right"><a class="button" href="/index.php"><span>返 回</span></a></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	<div class="bottom">
		<div class="left"></div>
		<div class="right"></div>
		<div class="center"></div>
	</div>
</div>
<!-- content -->