<!--各controller/action刷新的内容-->
<script type="text/javascript">
$(document).ready(function() {
	 	$(".tabNav a").removeClass("selected");
		$("#tab_account").addClass("selected");

});
</script>
<div id="content">
	<div class="top">
		<div class="left"></div>
		<div class="right"></div>
		<div class="center">
			<h1>用 户 中 心</h1>
		</div>
	</div>
	<div class="middle">
		<p>
			<a href="/customer/edit">编辑我的信息</a>
		</p>
		<p>
			<a href="/customer/orderhistory">查看订单历史</a>
		</p>


	</div>
	<div class="bottom">
		<div class="left"></div>
		<div class="right"></div>
		<div class="center"></div>
	</div>
</div>
<!-- content -->