<!--各controller/action刷新的内容-->
<div id="content">
	<div class="top">
		<div class="left"></div>
		<div class="right"></div>
		<div class="center">
			<h1>我的订单历史</h1>
		</div>
	</div>
	<div class="middle">
		<div style="display: inline-block; margin-bottom: 10px; width: 100%;">

		</div>

		<div class="pagination">
			<div class="results"></div>
		</div>
		<div class="buttons">
			<table>
				<tbody>
					<tr>
						<td align="right"><a class="button" href="/customer/account"><span>Continue</span></a></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	<div class="bottom">
		<div class="left"></div>
		<div class="right"></div>
		<div class="center"></div>
	</div>
</div>
<!-- content -->